"""create initial application schema

Revision ID: f86d36b27719
Revises: None
Create Date: 2026-10-01 17:42:32.159138

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86d36b27719'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_categories_code'))
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('feature_set', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('history_end_date', sa.Date(), nullable=False),
    sa.Column('forecast_start_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('horizon_days > 0', name=op.f('ck_forecast_runs_horizon_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs'))
    )
    op.create_table('model_metrics',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('feature_set', sa.String(length=100), nullable=False),
    sa.Column('dataset_split', sa.String(length=64), nullable=False),
    sa.Column('mae', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('wape', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metrics'))
    )
    op.create_table('suppliers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'INVENTORY_STAFF', name='user_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('purchase_orders',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('supplier_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ORDERED', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED', name='purchase_order_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('expected_arrival_date', sa.Date(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.BIGINT(), nullable=True),
    sa.Column('approved_by_user_id', sa.BIGINT(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_approved_by_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_table('forecast_values',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('forecast_run_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('horizon_day', sa.Integer(), nullable=False),
    sa.Column('predicted_demand', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('horizon_day > 0', name=op.f('ck_forecast_values_horizon_day_positive')),
    sa.CheckConstraint('predicted_demand >= 0', name=op.f('ck_forecast_values_predicted_demand_nonnegative')),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], name=op.f('fk_forecast_values_forecast_run_id_forecast_runs')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_forecast_values_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_values')),
    sa.UniqueConstraint('forecast_run_id', 'product_id', 'forecast_date', name='forecast_run_product_date')
    )
    op.create_index(op.f('ix_forecast_values_forecast_run_id'), 'forecast_values', ['forecast_run_id'], unique=False)
    op.create_index('ix_forecast_values_product_date', 'forecast_values', ['product_id', 'forecast_date'], unique=False)
    op.create_table('inventory',
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('on_hand >= 0', name=op.f('ck_inventory_on_hand_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_inventory'))
    )
    op.create_table('purchase_order_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('ordered_quantity', sa.Integer(), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ordered_quantity > 0', name=op.f('ck_purchase_order_items_ordered_quantity_positive')),
    sa.CheckConstraint('received_quantity <= ordered_quantity', name=op.f('ck_purchase_order_items_received_not_over_ordered')),
    sa.CheckConstraint('received_quantity >= 0', name=op.f('ck_purchase_order_items_received_quantity_nonnegative')),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name=op.f('ck_purchase_order_items_unit_cost_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_items_product_id_products')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_items_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items')),
    sa.UniqueConstraint('purchase_order_id', 'product_id', name='purchase_order_product')
    )
    op.create_table('reorder_recommendations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('forecast_run_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACCEPTED', 'MODIFIED', 'REJECTED', 'EXPIRED', name='recommendation_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_on_hand', sa.Integer(), nullable=False),
    sa.Column('incoming_quantity', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('recommended_quantity', sa.Integer(), nullable=False),
    sa.Column('approved_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.BIGINT(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('approved_quantity IS NULL OR approved_quantity >= 0', name=op.f('ck_reorder_recommendations_approved_quantity_nonnegative')),
    sa.CheckConstraint('current_on_hand >= 0', name=op.f('ck_reorder_recommendations_current_on_hand_nonnegative')),
    sa.CheckConstraint('incoming_quantity >= 0', name=op.f('ck_reorder_recommendations_incoming_quantity_nonnegative')),
    sa.CheckConstraint('lead_time_days > 0', name=op.f('ck_reorder_recommendations_lead_time_positive')),
    sa.CheckConstraint('recommended_quantity >= 0', name=op.f('ck_reorder_recommendations_recommended_quantity_nonnegative')),
    sa.CheckConstraint('reorder_point >= 0', name=op.f('ck_reorder_recommendations_reorder_point_nonnegative')),
    sa.CheckConstraint('safety_stock >= 0', name=op.f('ck_reorder_recommendations_safety_stock_nonnegative')),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['forecast_runs.id'], name=op.f('fk_reorder_recommendations_forecast_run_id_forecast_runs')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_reorder_recommendations_product_id_products')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('fk_reorder_recommendations_reviewed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reorder_recommendations'))
    )
    op.create_index('ix_reorder_recommendations_product_created', 'reorder_recommendations', ['product_id', 'created_at'], unique=False)
    op.create_index('ix_reorder_recommendations_status', 'reorder_recommendations', ['status'], unique=False)
    op.create_table('sales_daily',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity_sold >= 0', name=op.f('ck_sales_daily_quantity_sold_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_daily_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_daily')),
    sa.UniqueConstraint('product_id', 'sale_date', name='product_sale_date')
    )
    op.create_table('supplier_products',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('lead_time_days > 0', name=op.f('ck_supplier_products_lead_time_positive')),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name=op.f('ck_supplier_products_unit_cost_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_products_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_products_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_products')),
    sa.UniqueConstraint('supplier_id', 'product_id', name='supplier_product_pair')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('transaction_type', sa.Enum('RECEIPT', 'SALE', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', name='stock_transaction_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('purchase_order_item_id', sa.BIGINT(), nullable=True),
    sa.Column('sales_daily_id', sa.BIGINT(), nullable=True),
    sa.Column('created_by_user_id', sa.BIGINT(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_stock_transactions_quantity_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_stock_transactions_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_transactions_product_id_products')),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], name=op.f('fk_stock_transactions_purchase_order_item_id_purchase_order_items')),
    sa.ForeignKeyConstraint(['sales_daily_id'], ['sales_daily.id'], name=op.f('fk_stock_transactions_sales_daily_id_sales_daily')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transactions'))
    )
    op.create_index('ix_stock_transactions_product_occurred', 'stock_transactions', ['product_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL requires FK-supporting indexes to exist until their table is removed.
    # Dropping each dependent table removes its owned indexes safely.
    op.drop_table('stock_transactions')
    op.drop_table('supplier_products')
    op.drop_table('sales_daily')
    op.drop_table('reorder_recommendations')
    op.drop_table('purchase_order_items')
    op.drop_table('inventory')
    op.drop_table('forecast_values')
    op.drop_table('purchase_orders')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('model_metrics')
    op.drop_table('forecast_runs')
    op.drop_table('categories')
