import { useEffect, useRef, useState } from 'react'
import { BarChart3, Eye, EyeOff } from 'lucide-react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { useLocation, useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { api } from '../api/client'

export default function AuthPage({ initialMode }) {
  const [mode, setMode] = useState(initialMode); const [show, setShow] = useState(false); const loginRef = useRef(null); const registerRef = useRef(null); const navigate = useNavigate(); const location = useLocation(); const client = useQueryClient()
  useEffect(() => (mode === 'login' ? loginRef : registerRef).current?.focus(), [mode])
  const done = (user, message) => { client.setQueryData(['auth-me'], user); toast.success(message); navigate(location.state?.from || '/', { replace: true }) }
  const login = useMutation({ mutationFn: api.login, onSuccess: (user) => done(user, 'Welcome back'), onError: (error) => toast.error(error.message) }); const register = useMutation({ mutationFn: api.register, onSuccess: (user) => done(user, 'Account created'), onError: (error) => toast.error(error.message) })
  const flip = (next) => { setShow(false); setMode(next); navigate(next === 'login' ? '/login' : '/register', { replace: true, state: location.state }) }
  const password = (disabled) => <label>Password<span className="password-field"><input name="password" type={show ? 'text' : 'password'} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} minLength="12" disabled={disabled} required/><button type="button" disabled={disabled} onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff size={17}/> : <Eye size={17}/>}</button></span></label>
  return <main className="auth-page"><div className="auth-atmosphere one"/><div className="auth-atmosphere two"/><header className="auth-brand"><div className="brand-mark"><BarChart3 size={20}/></div><strong>Smart<span>Inventory</span></strong></header><section className={`auth-coin ${mode === 'register' ? 'is-flipped' : ''}`}><div className="auth-ring"/><div className="auth-card auth-login" aria-hidden={mode !== 'login'}><header><p className="eyebrow">Smart Inventory Market</p><h1>Welcome back</h1><p>Smarter stock decisions, powered by demand forecasting.</p></header><form onSubmit={(event) => { event.preventDefault(); login.mutate(Object.fromEntries(new FormData(event.currentTarget))) }}><label>Email<input ref={loginRef} name="email" type="email" autoComplete="email" disabled={mode !== 'login'} required/></label>{password(mode !== 'login')}<button className="auth-submit" disabled={login.isPending}>{login.isPending ? 'Signing in…' : 'Sign in'}</button></form><button className="auth-switch" type="button" onClick={() => flip('register')}>Create account</button></div><div className="auth-card auth-register" aria-hidden={mode !== 'register'}><header><p className="eyebrow">Smart Inventory Market</p><h1>Create account</h1><p>New accounts receive inventory-staff access.</p></header><form onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); if (values.password !== values.confirm_password) return toast.error('Passwords do not match.'); register.mutate(values) }}><label>Display name<input ref={registerRef} name="full_name" autoComplete="name" disabled={mode !== 'register'} required/></label><label>Email<input name="email" type="email" autoComplete="email" disabled={mode !== 'register'} required/></label>{password(mode !== 'register')}<label>Confirm password<input name="confirm_password" type={show ? 'text' : 'password'} autoComplete="new-password" minLength="12" disabled={mode !== 'register'} required/></label><button className="auth-submit" disabled={register.isPending}>{register.isPending ? 'Creating account…' : 'Create account'}</button></form><button className="auth-switch" type="button" onClick={() => flip('login')}>Back to sign in</button></div></section></main>
}
