import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus } from 'lucide-react'
import { toast } from 'sonner'
import { api } from '../api/client'
import { Badge, Button, Empty, Loading, Modal } from '../components/ui'
import { toneFor } from '../utils/status'

const tell = (error) => toast.error(error.message || 'Operation failed')
function PanelTitle({ title, text, action }) { return <header className="page-heading"><div><p className="eyebrow">Operations</p><h2>{title}</h2><p>{text}</p></div>{action}</header> }

export function ProductsPage() {
  const client = useQueryClient(); const [search, setSearch] = useState(''); const [editor, setEditor] = useState(null)
  const products = useQuery({ queryKey: ['products', search], queryFn: () => api.products({ limit: 100, search }) }); const categories = useQuery({ queryKey: ['categories'], queryFn: api.categories })
  const save = useMutation({ mutationFn: ({ id, data }) => id ? api.updateProduct(id, data) : api.createProduct(data), onSuccess: () => { client.invalidateQueries({ queryKey: ['products'] }); client.invalidateQueries({ queryKey: ['inventory'] }); toast.success('Product saved'); setEditor(null) }, onError: tell })
  if (products.isLoading || categories.isLoading) return <Loading />
  return <div className="stack"><PanelTitle title="Products" text="Maintain the active product catalog and its inventory identity." action={<Button onClick={() => setEditor({})}><Plus size={16}/>New product</Button>}/><div className="toolbar"><label>Search<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="SKU or product name" /></label><span>{products.data?.length || 0} products</span></div><article className="panel table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>Unit</th><th>Status</th><th /></tr></thead><tbody>{products.data?.map((p) => <tr key={p.id}><td className="mono">{p.sku}</td><td><strong>{p.name}</strong></td><td>{categories.data?.find((c) => c.id === p.category_id)?.name || '—'}</td><td>{p.unit}</td><td><Badge tone={p.is_active ? 'success' : 'neutral'}>{p.is_active ? 'ACTIVE' : 'INACTIVE'}</Badge></td><td><button className="link-button" onClick={() => setEditor(p)}>Edit</button></td></tr>)}</tbody></table>{!products.data?.length && <Empty title="No products">Create a product to start operational setup.</Empty>}</article>{editor && <ProductModal product={editor} categories={categories.data} onClose={() => setEditor(null)} onSave={(data) => save.mutate({ id: editor.id, data })} loading={save.isPending}/>}</div>
}
function ProductModal({ product, categories, onClose, onSave, loading }) { const [form, setForm] = useState({ sku: product.sku || '', name: product.name || '', category_id: product.category_id || categories[0]?.id || '', unit: product.unit || 'unit', is_active: product.is_active ?? true }); const submit = (e) => { e.preventDefault(); onSave({ ...form, category_id: Number(form.category_id) }) }; return <Modal title={product.id ? 'Edit product' : 'Create product'} onClose={onClose}><form className="form-grid" onSubmit={submit}><label>SKU<input required value={form.sku} onChange={(e) => setForm({...form, sku:e.target.value})}/></label><label>Product name<input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></label><label>Category<select value={form.category_id} onChange={(e) => setForm({...form,category_id:e.target.value})}>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Unit<input required value={form.unit} onChange={(e) => setForm({...form,unit:e.target.value})}/></label>{product.id && <label className="check"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({...form,is_active:e.target.checked})}/> Active product</label>}<footer><Button type="button" className="secondary" onClick={onClose}>Cancel</Button><Button loading={loading} type="submit">Save product</Button></footer></form></Modal> }

export function InventoryPage() { const client = useQueryClient(); const [adjust, setAdjust] = useState(null); const inventory = useQuery({queryKey:['inventory'],queryFn:api.inventory}); const transactions = useQuery({queryKey:['transactions'],queryFn:api.transactions}); const save = useMutation({mutationFn:({id,data})=>api.adjust(id,data),onSuccess:()=>{['inventory','transactions','decisions'].forEach((key)=>client.invalidateQueries({queryKey:[key]}));toast.success('Inventory adjustment recorded');setAdjust(null)},onError:tell}); if(inventory.isLoading||transactions.isLoading)return <Loading/>; return <div className="stack"><PanelTitle title="Inventory" text="On-hand inventory changes only through auditable adjustments and receipts."/><article className="panel table-wrap"><table><thead><tr><th>Product</th><th>On hand</th><th>Incoming</th><th>Position</th><th>Updated</th><th/></tr></thead><tbody>{inventory.data?.map((row)=><tr key={row.product_id}><td><strong>{row.product_name}</strong><small>{row.sku}</small></td><td>{row.on_hand}</td><td>{row.incoming_quantity}</td><td><strong>{row.inventory_position}</strong></td><td>{new Date(row.updated_at).toLocaleDateString()}</td><td><button className="link-button" onClick={()=>setAdjust(row)}>Adjust</button></td></tr>)}</tbody></table></article><article className="panel table-wrap"><header><h2>Transaction history</h2></header><table><thead><tr><th>Type</th><th>Product ID</th><th>Quantity</th><th>Reason</th><th>Time</th></tr></thead><tbody>{transactions.data?.slice(0,20).map((row)=><tr key={row.id}><td><Badge tone={toneFor(row.transaction_type)}>{row.transaction_type}</Badge></td><td>{row.product_id}</td><td>{row.quantity}</td><td>{row.reason || '—'}</td><td>{new Date(row.occurred_at).toLocaleString()}</td></tr>)}</tbody></table></article>{adjust&&<AdjustmentModal item={adjust} onClose={()=>setAdjust(null)} onSave={(data)=>save.mutate({id:adjust.product_id,data})} loading={save.isPending}/>}</div> }
function AdjustmentModal({item,onClose,onSave,loading}){const [form,setForm]=useState({transaction_type:'ADJUSTMENT_IN',quantity:1,reason:''});return <Modal title={`Adjust ${item.sku}`} onClose={onClose}><form className="form-grid" onSubmit={(e)=>{e.preventDefault();onSave({...form,quantity:Number(form.quantity)})}}><p className="callout">Inventory is not freely editable. This creates an immutable adjustment record.</p><label>Adjustment type<select value={form.transaction_type} onChange={(e)=>setForm({...form,transaction_type:e.target.value})}><option>ADJUSTMENT_IN</option><option>ADJUSTMENT_OUT</option></select></label><label>Quantity<input type="number" min="1" value={form.quantity} onChange={(e)=>setForm({...form,quantity:e.target.value})}/></label><label>Reason<textarea required value={form.reason} onChange={(e)=>setForm({...form,reason:e.target.value})}/></label><footer><Button type="button" className="secondary" onClick={onClose}>Cancel</Button><Button loading={loading}>Record adjustment</Button></footer></form></Modal>}

export function SuppliersPage(){const client=useQueryClient();const [open,setOpen]=useState(false);const suppliers=useQuery({queryKey:['suppliers'],queryFn:api.suppliers});const mappings=useQuery({queryKey:['supplierProducts'],queryFn:api.supplierProducts});const products=useQuery({queryKey:['products'],queryFn:()=>api.products({limit:100})});const save=useMutation({mutationFn:api.createSupplier,onSuccess:()=>{client.invalidateQueries({queryKey:['suppliers']});toast.success('Supplier created');setOpen(false)},onError:tell});const map=useMutation({mutationFn:api.createSupplierProduct,onSuccess:()=>{client.invalidateQueries({queryKey:['supplierProducts']});client.invalidateQueries({queryKey:['decisions']});toast.success('Supplier mapping saved')},onError:tell});if(suppliers.isLoading||mappings.isLoading||products.isLoading)return <Loading/>;return <div className="stack"><PanelTitle title="Suppliers" text="Supplier mappings provide the lead-time context for inventory decisions." action={<Button onClick={()=>setOpen(true)}><Plus size={16}/>New supplier</Button>}/><section className="two-grid"><article className="panel table-wrap"><header><h2>Suppliers</h2></header><table><thead><tr><th>Supplier</th><th>Contact</th><th>Status</th></tr></thead><tbody>{suppliers.data?.map((s)=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.code}</small></td><td>{s.email||s.phone||'—'}</td><td><Badge tone={s.is_active?'success':'neutral'}>{s.is_active?'ACTIVE':'INACTIVE'}</Badge></td></tr>)}</tbody></table></article><article className="panel"><header><h2>Product mapping</h2></header><MappingForm suppliers={suppliers.data} products={products.data} onSave={map.mutate} loading={map.isPending}/><div className="mini-list">{mappings.data?.map((m)=><div key={m.id}><div><strong>{products.data.find(p=>p.id===m.product_id)?.sku||`Product #${m.product_id}`}</strong><span>Lead time {m.lead_time_days} days · {m.unit_cost||'No unit cost'}</span></div>{m.is_preferred&&<Badge tone="success">PREFERRED</Badge>}</div>)}</div></article></section>{open&&<SupplierModal onClose={()=>setOpen(false)} onSave={save.mutate} loading={save.isPending}/>}</div>}
function SupplierModal({onClose,onSave,loading}){const [form,setForm]=useState({code:'',name:'',email:'',phone:''});return <Modal title="Create supplier" onClose={onClose}><form className="form-grid" onSubmit={(e)=>{e.preventDefault();onSave(form)}}><label>Supplier code<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><footer><Button type="button" className="secondary" onClick={onClose}>Cancel</Button><Button loading={loading}>Save supplier</Button></footer></form></Modal>}
function MappingForm({suppliers,products,onSave,loading}){const [form,setForm]=useState({supplier_id:'',product_id:'',lead_time_days:7,unit_cost:'',is_preferred:false});return <form className="inline-form" onSubmit={(e)=>{e.preventDefault();onSave({...form,supplier_id:Number(form.supplier_id),product_id:Number(form.product_id),lead_time_days:Number(form.lead_time_days),unit_cost:form.unit_cost||null})}}><select required value={form.supplier_id} onChange={e=>setForm({...form,supplier_id:e.target.value})}><option value="">Supplier</option>{suppliers.filter(s=>s.is_active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select required value={form.product_id} onChange={e=>setForm({...form,product_id:e.target.value})}><option value="">Product</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku}</option>)}</select><input type="number" min="1" placeholder="Lead days" value={form.lead_time_days} onChange={e=>setForm({...form,lead_time_days:e.target.value})}/><label className="check"><input type="checkbox" checked={form.is_preferred} onChange={e=>setForm({...form,is_preferred:e.target.checked})}/> Preferred</label><Button loading={loading}>Map</Button></form>}
