import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, ArrowDownToLine, Boxes, ClipboardCheck, PackageCheck } from 'lucide-react'
import { Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../api/client'
import { Badge, Empty, Loading } from '../components/ui'
import { toneFor } from '../utils/status'

const cards = [{ key: 'products', label: 'Tracked products', icon: Boxes }, { key: 'onHand', label: 'On-hand units', icon: PackageCheck }, { key: 'incoming', label: 'Incoming units', icon: ArrowDownToLine }, { key: 'new', label: 'New recommendations', icon: ClipboardCheck }]

export default function DashboardPage() {
  const inventory = useQuery({ queryKey: ['inventory'], queryFn: api.inventory })
  const products = useQuery({ queryKey: ['products'], queryFn: () => api.products({ limit: 100 }) })
  const decisions = useQuery({ queryKey: ['decisions'], queryFn: api.decisions })
  const recommendations = useQuery({ queryKey: ['recommendations'], queryFn: api.recommendations })
  const orders = useQuery({ queryKey: ['orders'], queryFn: api.purchaseOrders })
  if ([inventory, products, decisions, recommendations, orders].some((q) => q.isLoading)) return <Loading />
  const inv = inventory.data || []; const dec = decisions.data || []; const rec = recommendations.data || []
  const values = { products: (products.data || []).length, onHand: inv.reduce((sum, item) => sum + item.on_hand, 0), incoming: inv.reduce((sum, item) => sum + item.incoming_quantity, 0), new: rec.filter((item) => item.status === 'NEW').length }
  const risks = ['STOCKOUT_RISK', 'REORDER_NEEDED', 'HEALTHY', 'OVERSTOCK_RISK'].map((name) => ({ name: name.replaceAll('_', ' '), count: dec.filter((item) => item.risk_status === name).length, color: { STOCKOUT_RISK: '#d9534f', REORDER_NEEDED: '#d69328', HEALTHY: '#39956c', OVERSTOCK_RISK: '#5e79b8' }[name] }))
  return <div className="stack"><section className="hero-copy"><div><p className="eyebrow">Decision support overview</p><h2>Inventory signals, ready for review.</h2><p>Live operational data informs every signal. Recommendations remain human-reviewed.</p></div><div className="hero-note"><AlertTriangle size={18}/><span>Forecasts are M5-compatible thesis data only.</span></div></section><section className="kpis">{cards.map(({ key, label, icon: Icon }) => <article className="kpi" key={key}><div><span>{label}</span><strong>{values[key].toLocaleString()}</strong></div><i><Icon size={20}/></i></article>)}</section><section className="two-grid"><article className="panel chart-panel"><header><div><p className="eyebrow">Portfolio health</p><h2>Risk distribution</h2></div></header>{dec.length ? <ResponsiveContainer width="100%" height={250}><BarChart data={risks}><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="count" radius={[5,5,0,0]}>{risks.map((entry) => <Cell key={entry.name} fill={entry.color}/>)}</Bar></BarChart></ResponsiveContainer> : <Empty title="No decision data">Add supplier mappings and generate a compatible forecast to calculate risk.</Empty>}</article><article className="panel"><header><div><p className="eyebrow">Attention queue</p><h2>Recent recommendations</h2></div></header>{rec.length ? <div className="mini-list">{rec.slice(0,5).map((item) => <div key={item.id}><div><strong>Product #{item.product_id}</strong><span>Recommended {item.recommended_quantity} units</span></div><Badge tone={toneFor(item.status)}>{item.status}</Badge></div>)}</div> : <Empty title="No recommendations">No reorder recommendations require review.</Empty>}</article></section><section className="two-grid"><article className="panel"><header><h2>Inventory attention</h2></header>{dec.filter((d) => d.risk_status !== 'HEALTHY').length ? <div className="mini-list">{dec.filter((d) => d.risk_status !== 'HEALTHY').slice(0,5).map((item) => <div key={item.product_id}><div><strong>{item.sku}</strong><span>{item.inventory_position} position · {item.recommended_quantity} suggested</span></div><Badge tone={toneFor(item.risk_status)}>{item.risk_status}</Badge></div>)}</div> : <Empty title="Inventory looks balanced">Risk calculations will appear here when eligible.</Empty>}</article><article className="panel"><header><h2>Recent purchase orders</h2></header>{(orders.data || []).length ? <div className="mini-list">{orders.data.slice(0,5).map((item) => <div key={item.id}><div><strong>{item.po_number}</strong><span>{item.items.length} line item{item.items.length === 1 ? '' : 's'}</span></div><Badge tone={toneFor(item.status)}>{item.status}</Badge></div>)}</div> : <Empty title="No purchase orders">Create your first purchase order from the operations pages.</Empty>}</article></section></div>
}
